/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedFeedbackRouteImport } from './routes/_protected/feedback'
import { Route as ProtectedMyDocumentsRouteImport } from './routes/_protected/my-documents'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ProtectedDocumentsDocumentIdRouteImport } from './routes/_protected/documents/$documentId'
import { Route as ProtectedDocumentsNewRouteImport } from './routes/_protected/documents/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPdfsDocumentIdRouteImport } from './routes/api/pdfs/$documentId'
import { Route as ProtectedDocumentsDocumentIdIndexRouteImport } from './routes/_protected/documents/$documentId/index'
import { Route as ProtectedDocumentsDocumentIdReaderRouteImport } from './routes/_protected/documents/$documentId/_reader'
import { Route as ProtectedDocumentsDocumentIdReaderFicheRouteImport } from './routes/_protected/documents/$documentId/_reader/fiche'
import { Route as ProtectedDocumentsDocumentIdReaderNoteRouteImport } from './routes/_protected/documents/$documentId/_reader/note'
import { Route as ProtectedDocumentsDocumentIdReaderReasoningRouteImport } from './routes/_protected/documents/$documentId/_reader/reasoning'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeedbackRoute = ProtectedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyDocumentsRoute = ProtectedMyDocumentsRouteImport.update({
  id: '/my-documents',
  path: '/my-documents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDocumentsDocumentIdRoute =
  ProtectedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDocumentsNewRoute = ProtectedDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfsDocumentIdRoute = ApiPdfsDocumentIdRouteImport.update({
  id: '/api/pdfs/$documentId',
  path: '/api/pdfs/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDocumentsDocumentIdIndexRoute =
  ProtectedDocumentsDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDocumentsDocumentIdRoute,
  } as any)
const ProtectedDocumentsDocumentIdReaderRoute =
  ProtectedDocumentsDocumentIdReaderRouteImport.update({
    id: '/_reader',
    getParentRoute: () => ProtectedDocumentsDocumentIdRoute,
  } as any)
const ProtectedDocumentsDocumentIdReaderFicheRoute =
  ProtectedDocumentsDocumentIdReaderFicheRouteImport.update({
    id: '/fiche',
    path: '/fiche',
    getParentRoute: () => ProtectedDocumentsDocumentIdReaderRoute,
  } as any)
const ProtectedDocumentsDocumentIdReaderNoteRoute =
  ProtectedDocumentsDocumentIdReaderNoteRouteImport.update({
    id: '/note',
    path: '/note',
    getParentRoute: () => ProtectedDocumentsDocumentIdReaderRoute,
  } as any)
const ProtectedDocumentsDocumentIdReaderReasoningRoute =
  ProtectedDocumentsDocumentIdReaderReasoningRouteImport.update({
    id: '/reasoning',
    path: '/reasoning',
    getParentRoute: () => ProtectedDocumentsDocumentIdReaderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/my-documents': typeof ProtectedMyDocumentsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/documents/$documentId': typeof ProtectedDocumentsDocumentIdRouteWithChildren
  '/documents/new': typeof ProtectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdfs/$documentId': typeof ApiPdfsDocumentIdRoute
  '/documents/$documentId/': typeof ProtectedDocumentsDocumentIdIndexRoute
  '/documents/$documentId/fiche': typeof ProtectedDocumentsDocumentIdReaderFicheRoute
  '/documents/$documentId/note': typeof ProtectedDocumentsDocumentIdReaderNoteRoute
  '/documents/$documentId/reasoning': typeof ProtectedDocumentsDocumentIdReaderReasoningRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/my-documents': typeof ProtectedMyDocumentsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/': typeof ProtectedIndexRoute
  '/documents/new': typeof ProtectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdfs/$documentId': typeof ApiPdfsDocumentIdRoute
  '/documents/$documentId': typeof ProtectedDocumentsDocumentIdIndexRoute
  '/documents/$documentId/fiche': typeof ProtectedDocumentsDocumentIdReaderFicheRoute
  '/documents/$documentId/note': typeof ProtectedDocumentsDocumentIdReaderNoteRoute
  '/documents/$documentId/reasoning': typeof ProtectedDocumentsDocumentIdReaderReasoningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/feedback': typeof ProtectedFeedbackRoute
  '/_protected/my-documents': typeof ProtectedMyDocumentsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/documents/$documentId': typeof ProtectedDocumentsDocumentIdRouteWithChildren
  '/_protected/documents/new': typeof ProtectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdfs/$documentId': typeof ApiPdfsDocumentIdRoute
  '/_protected/documents/$documentId/_reader': typeof ProtectedDocumentsDocumentIdReaderRouteWithChildren
  '/_protected/documents/$documentId/': typeof ProtectedDocumentsDocumentIdIndexRoute
  '/_protected/documents/$documentId/_reader/fiche': typeof ProtectedDocumentsDocumentIdReaderFicheRoute
  '/_protected/documents/$documentId/_reader/note': typeof ProtectedDocumentsDocumentIdReaderNoteRoute
  '/_protected/documents/$documentId/_reader/reasoning': typeof ProtectedDocumentsDocumentIdReaderReasoningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/feedback'
    | '/my-documents'
    | '/api/documents'
    | '/documents/$documentId'
    | '/documents/new'
    | '/api/auth/$'
    | '/api/pdfs/$documentId'
    | '/documents/$documentId/'
    | '/documents/$documentId/fiche'
    | '/documents/$documentId/note'
    | '/documents/$documentId/reasoning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/feedback'
    | '/my-documents'
    | '/api/documents'
    | '/'
    | '/documents/new'
    | '/api/auth/$'
    | '/api/pdfs/$documentId'
    | '/documents/$documentId'
    | '/documents/$documentId/fiche'
    | '/documents/$documentId/note'
    | '/documents/$documentId/reasoning'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/feedback'
    | '/_protected/my-documents'
    | '/api/documents'
    | '/_protected/'
    | '/_protected/documents/$documentId'
    | '/_protected/documents/new'
    | '/api/auth/$'
    | '/api/pdfs/$documentId'
    | '/_protected/documents/$documentId/_reader'
    | '/_protected/documents/$documentId/'
    | '/_protected/documents/$documentId/_reader/fiche'
    | '/_protected/documents/$documentId/_reader/note'
    | '/_protected/documents/$documentId/_reader/reasoning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPdfsDocumentIdRoute: typeof ApiPdfsDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/feedback': {
      id: '/_protected/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof ProtectedFeedbackRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-documents': {
      id: '/_protected/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof ProtectedMyDocumentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/documents/$documentId': {
      id: '/_protected/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents/new': {
      id: '/_protected/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof ProtectedDocumentsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdfs/$documentId': {
      id: '/api/pdfs/$documentId'
      path: '/api/pdfs/$documentId'
      fullPath: '/api/pdfs/$documentId'
      preLoaderRoute: typeof ApiPdfsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/documents/$documentId/': {
      id: '/_protected/documents/$documentId/'
      path: '/'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof ProtectedDocumentsDocumentIdRoute
    }
    '/_protected/documents/$documentId/_reader': {
      id: '/_protected/documents/$documentId/_reader'
      path: ''
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdReaderRouteImport
      parentRoute: typeof ProtectedDocumentsDocumentIdRoute
    }
    '/_protected/documents/$documentId/_reader/fiche': {
      id: '/_protected/documents/$documentId/_reader/fiche'
      path: '/fiche'
      fullPath: '/documents/$documentId/fiche'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdReaderFicheRouteImport
      parentRoute: typeof ProtectedDocumentsDocumentIdReaderRoute
    }
    '/_protected/documents/$documentId/_reader/note': {
      id: '/_protected/documents/$documentId/_reader/note'
      path: '/note'
      fullPath: '/documents/$documentId/note'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdReaderNoteRouteImport
      parentRoute: typeof ProtectedDocumentsDocumentIdReaderRoute
    }
    '/_protected/documents/$documentId/_reader/reasoning': {
      id: '/_protected/documents/$documentId/_reader/reasoning'
      path: '/reasoning'
      fullPath: '/documents/$documentId/reasoning'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdReaderReasoningRouteImport
      parentRoute: typeof ProtectedDocumentsDocumentIdReaderRoute
    }
  }
}

interface ProtectedDocumentsDocumentIdReaderRouteChildren {
  ProtectedDocumentsDocumentIdReaderFicheRoute: typeof ProtectedDocumentsDocumentIdReaderFicheRoute
  ProtectedDocumentsDocumentIdReaderNoteRoute: typeof ProtectedDocumentsDocumentIdReaderNoteRoute
  ProtectedDocumentsDocumentIdReaderReasoningRoute: typeof ProtectedDocumentsDocumentIdReaderReasoningRoute
}

const ProtectedDocumentsDocumentIdReaderRouteChildren: ProtectedDocumentsDocumentIdReaderRouteChildren =
  {
    ProtectedDocumentsDocumentIdReaderFicheRoute:
      ProtectedDocumentsDocumentIdReaderFicheRoute,
    ProtectedDocumentsDocumentIdReaderNoteRoute:
      ProtectedDocumentsDocumentIdReaderNoteRoute,
    ProtectedDocumentsDocumentIdReaderReasoningRoute:
      ProtectedDocumentsDocumentIdReaderReasoningRoute,
  }

const ProtectedDocumentsDocumentIdReaderRouteWithChildren =
  ProtectedDocumentsDocumentIdReaderRoute._addFileChildren(
    ProtectedDocumentsDocumentIdReaderRouteChildren,
  )

interface ProtectedDocumentsDocumentIdRouteChildren {
  ProtectedDocumentsDocumentIdReaderRoute: typeof ProtectedDocumentsDocumentIdReaderRouteWithChildren
  ProtectedDocumentsDocumentIdIndexRoute: typeof ProtectedDocumentsDocumentIdIndexRoute
}

const ProtectedDocumentsDocumentIdRouteChildren: ProtectedDocumentsDocumentIdRouteChildren =
  {
    ProtectedDocumentsDocumentIdReaderRoute:
      ProtectedDocumentsDocumentIdReaderRouteWithChildren,
    ProtectedDocumentsDocumentIdIndexRoute:
      ProtectedDocumentsDocumentIdIndexRoute,
  }

const ProtectedDocumentsDocumentIdRouteWithChildren =
  ProtectedDocumentsDocumentIdRoute._addFileChildren(
    ProtectedDocumentsDocumentIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedFeedbackRoute: typeof ProtectedFeedbackRoute
  ProtectedMyDocumentsRoute: typeof ProtectedMyDocumentsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDocumentsDocumentIdRoute: typeof ProtectedDocumentsDocumentIdRouteWithChildren
  ProtectedDocumentsNewRoute: typeof ProtectedDocumentsNewRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFeedbackRoute: ProtectedFeedbackRoute,
  ProtectedMyDocumentsRoute: ProtectedMyDocumentsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDocumentsDocumentIdRoute:
    ProtectedDocumentsDocumentIdRouteWithChildren,
  ProtectedDocumentsNewRoute: ProtectedDocumentsNewRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPdfsDocumentIdRoute: ApiPdfsDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
